### ISSUE TITLE
Docs: Fix prettier precommit

### ISSUE THREAD

**Issue by agritheory** [agritheory/test_utils#63]
The precommit mirror we're using has been archived. We can run Prettier directly. This means that we _might_ get different versions, but I'm willing to deal with that, I think. 

```
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier -c . --config .prettierrc.cjs --ignore-path .prettierignore
        language: system
```
